#new#set -g display-time 3000
#new##set -g status-bg black
#new##set -g status-fg cyan
#new##set-window-option -g window-status-current-attr bright,reverse
#new##set-window-option -g window-status-current-bg cyan
#new##set-window-option -g window-status-current-fg black
#new#unbind C-b
#new#set -g prefix C-a
#new#bind C-a last-window
#new#bind a send-prefix
#new#bind C-n next-window
#new#bind C-p previous-window
#new#bind ^H previous-window
#new#bind C-c new-window

#### COLOUR (Solarized dark)

#new## default statusbar colors
#new#set-option -g status-bg black #base02
#new#set-option -g status-fg yellow #yellow
#new#set-option -g status-attr default

#new## default window title colors
#new#set-window-option -g window-status-fg brightblue #base0
#new#set-window-option -g window-status-bg default
#new##set-window-option -g window-status-attr dim

# active window title colors
#new#set-window-option -g window-status-current-fg brightred #orange
#new#set-window-option -g window-status-current-bg default
#new##set-window-option -g window-status-current-attr bright

# pane border
#new#set-option -g pane-border-fg black #base02
#new#set-option -g pane-active-border-fg brightgreen #base01

# message text
#new#set-option -g message-bg black #base02
#new#set-option -g message-fg brightred #orange

# pane number display
#new#set-option -g display-panes-active-colour blue #blue
#new#set-option -g display-panes-colour brightred #orange

# clock
#new#set-window-option -g clock-mode-colour green #green

#new#set -g default-terminal "screen-256color"

# Allow local customization in ~/.tmux_local.conf
if-shell "[ -f ~/.tmux_local.conf ]" 'source ~/.tmux_local.conf'
