# ~/.config/kitty/common.conf
font_family FiraCode Nerd Font
font_size 14.0
term xterm-kitty
scrollback_lines 10000
shell_integration enabled
copy_on_select no
strip_trailing_spaces smart
tab_bar_style powerline
tab_powerline_style slanted
include themes/catppuccin-mocha.conf
