# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ${HOME}/.zshrc_local_before ]; then
    source ${HOME}/.zshrc_local_before
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="minimal"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

export ZSH_AUTOSUGGEST_USE_ASYNC='true'

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
if (( ${+plugins} )); then
	#echo "plugins already set, using them"
else
	plugins=(git thefuck catimg git-extras z zsh-syntax-highlighting macos brew mosh)
fi

# User configuration

export PATH="$PATH:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:$HOME/.local/bin:$HOME/bin:$HOME/.cargo/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

DEFAULT_USER="simon"

# 1) Environment
#export VDPAU_DRIVER="va_gl"
export EDITOR="vim"

# 2) Aliases
#alias pbcopy='xsel --clipboard --input'
#alias pbpaste='xsel --clipboard --output'

alias ll='ls -al --color=auto'
alias rr='ssh -l root'
alias 644='chmod 644'
alias 755='chmod 755'
alias rot13='tr a-zA-Z n-za-mN-ZA-M'
alias prove='PERL5OPT=-MAcme::require::case prove'
alias proveall='prove -j9 --state=slow,save -lr t'

# 2a) Very powerful zsh aliases
#alias -s tex=vim
#alias -s latex=vim
#alias -s toml=vim
#alias -s rs=vim
#alias -s conf=vim
#alias -s jpg=eog
#alias -s png=eog
#alias -s pdf=evince

# 3) Scripts and such
#test -f ~/.keychain/`uname -n`-sh && source ~/.keychain/`uname -n`-sh
#test -f ~/.keychain/`uname -n`-sh && source ~/.keychain/`uname -n`-sh-gpg
#test -x /usr/bin/keychain && eval `keychain --agents ssh,gpg --eval $HOME/.ssh/id_dsa $HOME/.ssh/id_ecdsa $HOME/.ssh/id_ed25519 $HOME/.ssh/id_rsa 4FAE5107`
#test -f ~/.keychain/`uname -n`-sh && source ~/.keychain/`uname -n`-sh
#test -f ~/.keychain/`uname -n`-sh-gpg && source ~/.keychain/`uname -n`-sh-gpg
if [ `uname -s` = 'Linux' ]; then
	test -x /usr/bin/xrdb && xrdb -DSOLARIZED_DARK -merge ${HOME}/.Xresources
fi

# 4) ZSH stuff
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ${HOME}/.zsh/cache
#eval $(thefuck --alias)
setopt HIST_IGNORE_DUPS
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')
setopt RM_STAR_WAIT
export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";
# enable tab completion for dcfldd :)
compdef dcfldd=dd
# Set directory colors
eval $(dircolors $HOME/.dir_colors)

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ${HOME}/.zshrc_local_after ]; then
    source ${HOME}/.zshrc_local_after
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
